### ISSUE TITLE
make 2.5 master

### ISSUE THREAD

**Issue by fgregg** [datamade/django-councilmatic#269]
would it be possible to merge the 2.5 branch into master? it would be one less thing for me to remember to do every occasional time I come to this repo? 

If we can't do that for some reason, can we make 2.5 the default branch?

![Screenshot_2020-08-04 datamade django-councilmatic](https://user-images.githubusercontent.com/536941/89299266-69ce6980-d634-11ea-9d5a-4627fdcf9859.png)

**Comment by hancush** [comment]
Oh, great question (and I have the same problem 😅).

IIRC, we're maintaining the 0.x series on master because NYC still relies on it, and merging 2.5 would make it difficult to patch bugs to the legacy version. With that said, AFAIK, we don't have a current maintenance agreement for NYC, and package versions are EOL'ed all the time.

So, if we're prepared to say we're no longer developing the 0.x version of `django-councilmatic`, then I think we can merge. If not, I'd be fine switching the default branch!

Thoughts, @fgregg?

**Comment by fgregg** [comment]
let's merge!

**Comment by fgregg** [comment]
let's please do this so code search will work, LOL.

**Comment by fgregg** [comment]
it ended up that there were merge conflicts with master. I didn't want to deal with those right now, so I ended up making 2.5 the default branch for github. this addresses the annoyances that we had, I think @hancush
