### ISSUE TITLE
Turn on travis tests

### ISSUE THREAD

**Issue by patcon** [datamade/django-councilmatic#60]
Any thoughts on enabled travis for the flake8 checks, and maybe adding a badge to the README?
https://travis-ci.org/datamade/django-councilmatic/

Might need to add `sudo: false` like james added here:
https://github.com/opencivicdata/scrapers-ca/blob/master/.travis.yml#L1

**Comment by cathydeng** [comment]
imo travis is best for indicating whether a build is passing/failing. if we don't have other tests, I don't think it makes sense to have a travis badge just for style checks.

also, if we want to check builds, it'd really make more sense to do it in each city's councilmatic, b/c a lot depends on how the pieces fit together, & as such it's unclear what it means for the django-councilmatic build to "fail"

however, if you can think of good tests that belong here in order to make sure the code is valid & working, I'm happy to discuss

**Comment by patcon** [comment]
Ah, ok, that makes sense with the badge. But are you still saying you'd prefer not to enable travis on PRs for style checks? To clarify, it doesn't block merge, it just provides feedback that someone might choose to willingly act on

**Comment by patcon** [comment]
Can we revisit this? ie. enable the travis tests on PR's [here](https://travis-ci.org/datamade/django-councilmatic/).

There are some style inconsistencies that are showing up as red in my IDE, and I'd like to fix them up, but it feels less fruitful if the tests aren't running some place public, and so no one else is aware and helping combat entropy :)
