### ISSUE TITLE
Sponsorships should also be related to Organizations

### ISSUE THREAD

**Issue by evz** [datamade/django-councilmatic#85]
The way our sponsorship model is currently put together, it is only related to people. We should also relate it to organizations because OCD allows for that.

@fgregg Does that jive with your understanding? We noticed in LA Metro that many of the sponsorships are actually organizations (whereas with other councilmatics, they have always been people)

**Comment by fgregg** [comment]
Yes, this is what is in the data. I think it's kind of odd, though. Not
sure whether they mean something else and they are overloading granicus's
data model.



On Fri, Oct 14, 2016 at 12:30 PM Eric van Zanten <notifications@github.com>
wrote:

The way our sponsorship model is currently put together, it is only related
to people. We should also relate it to organizations because OCD allows for
that.

@fgregg <https://github.com/fgregg> Does that jive with your understanding?
We noticed in LA Metro that many of the sponsorships are actually
organizations (whereas with other councilmatics, they have always been
people)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/datamade/django-councilmatic/issues/85>, or mute the
thread

**Comment by evz** [comment]
OK. Well, it seems like we ought to fix this at the very least. How does the scraper figure out what kind of entity the sponsor is? Is it possible that other entity types will end up being a sponsor?
